params:
  - params.yaml
stages:
  prepare_cleaning:
    cmd: uv run ${prepare.cleaning.filename} ${dataset_path}
    deps:
      - ${prepare.cleaning.filename}
      - ${dataset_path}
    outs:
      - data/processed/cleaned
      - logs/cleaning.log
      - labels.txt
  prepare_normalize:
    cmd: uv run ${prepare.normalization.filename} data/processed/cleaned
    deps:
      - ${prepare.normalization.filename}
      - data/processed/cleaned
    outs:
      - data/processed/normalized
      - logs/normalize.log
  prepare_sampling:
    cmd: uv run ${prepare.sampling.filename} data/processed/normalized/train
    deps:
      - ${prepare.sampling.filename}
      - data/processed/normalized/train
    outs:
      - data/processed/sampled
      - logs/sampling.log
  train:
    cmd: uv run ${train.filename} data/processed/sampled
    deps:
      - ${train.filename}
      - data/processed/sampled
    outs:
      - models
      - logs/train.log
      - logs/train_result.log
  evaluate:
    cmd: uv run ${evaluate.filename} data/processed/normalized/test
    deps:
      - ${evaluate.filename}
      - models
      - data/processed/normalized/test
    outs:
      - evaluate
      - logs/evaluate.log