params:
  - params.yaml
  - mlflow.experiment_prefix
  - mlflow.tracking_uri
stages:
  prepare_cleaning:
    cmd: uv run ${prepare.cleaning.filename} ${dataset_path}
    params:
      - prepare.adjustment.attempted
      - prepare.adjustment.combine_web_attack
      - prepare.adjustment.tool_separate
    deps:
      - ${prepare.cleaning.filename}
      - ${dataset_path}
    outs:
      - data/processed/cleaned
      - logs/cleaning.log
      - labels.txt
  prepare_normalize:
    cmd: uv run ${prepare.normalization.filename} data/processed/cleaned
    params:
      - prepare.normalize_method
      - prepare.test_size
    deps:
      - ${prepare.normalization.filename}
      - data/processed/cleaned
    outs:
      - data/processed/normalized
      - logs/normalize.log
  prepare_sampling:
    cmd: uv run ${prepare.sampling.filename} data/processed/normalized/train
    params:
      - prepare.oversampling.method
      - prepare.oversampling.params
    deps:
      - ${prepare.sampling.filename}
      - data/processed/normalized/train
    outs:
      - data/processed/sampled
      - logs/sampling.log
  train:
    cmd: uv run ${train.filename} data/processed/sampled
    params:
      - train.protocol_dim
      - train.port_dim
      - train.update_target_steps
      - train.batch_size
      - train.gamma
      - train.eps_start
      - train.eps_end
      - train.eps_decay
      - train.tau
      - train.lr
      - train.memory_size
      - train.n_episodes
      - train.sample_size
    deps:
      - ${train.filename}
      - data/processed/sampled
    outs:
      - models
      - logs/train.log
      - logs/train_result.log
      - train/plots
  evaluate:
    cmd: uv run ${evaluate.filename} data/processed/normalized/test
    deps:
      - ${evaluate.filename}
      - models
      - data/processed/normalized/test
    outs:
      - evaluate
      - logs/evaluate.log